# Generated by Django 5.1.2 on 2024-10-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uzs', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
