# Generated by Django 5.1.2 on 2024-10-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_productmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
